language: python
python:
    - "2.7"

branches:
    only:
        - master

git:
    submodules: false

install:
    - pip install sphinx tox simplejson MySQL-python pylint autopep8
    - pip install inspektor
    - pip install -r requirements.txt --use-mirrors

script:
    - ./utils/unittest_suite_nose.py -c .nose.cfg
    - inspekt lint
